# constants.py
class Texts:
    def __init__(self, language="en"):
        self.language = language
        self.texts = {
            "en": {
                "page_title": "GoldJack",
                "title": "GoldJack",
                "team_scores": "Hand History",
                "stats_actions": "Intelligent Blackjack Assistant with Card Detection",
                "team_a": "Your Hand",
                "team_b": "Dealer's Hand",
                "cards_team_a": "Your Cards",
                "cards_team_b": "Dealer's Cards",
                "points": "points",
                "take_snapshot": "Detect Cards",
                "capturing_cards": "Detecting cards... Please wait.",
                "cards_detected": "Cards detected successfully!",
                "no_cards_detected": "No cards detected. Please try again.",
                "flip_cards": "Swap Hands",
                "scoring_options": "Decision Analysis",
                "game_mode": "Strategy",
                "bonus_points_team_a": "Bet (Your Hand)",
                "bonus_points_team_b": "Bet (Dealer)",
                "team_a_last_10": "Did you win the last hand?",
                "update_scores": "Record Result",
                "scores_updated": "Result recorded successfully!",
                "revert_last_round": "Undo Last Hand",
                "start_new_game": "New Session",
                "new_game_started": "New session started successfully!",
                "game_modes": ["Hit", "Stand", "Double", "Split"],
                "image_analyzed": "Analyzed image",
                "upload_image": "Upload a card image",
                "num_players": "Number of players",
                "detection_mode": "Detection mode",
                "manual": "Manual",
                "automatic": "Automatic",
                "auto_detect_message": "The number of players will be detected automatically.",
                "players_detected": "Detected Players",
                "player": "Player",
                "no_dealer_detected": "⚠️ No dealer detected.",
                "not_enough_cards": "⚠️ At least 2 cards are needed to give a recommendation.",
                "player_hand": "Hand",
                "dealer_upcard": "Dealer's upcard",
                "hit_desc": "Request another card.",
                "stand_desc": "Stand. Your hand is strong enough.",
                "double_desc": "Double your bet and receive exactly one more card.",
                "split_desc": "Split your pair into two independent hands.",
                "blackjack_desc": "Blackjack! You win automatically.",
                "bust_desc": "You've gone over 21. You lose automatically.",
                "players_detected_debug": "players detected"
            },
            "es": {
                "page_title": "GoldJack - Asistente de Blackjack",
                "title": "GoldJack ",
                "team_scores": "Historial de Manos",
                "stats_actions": "Asistente Inteligente de Blackjack mediante Detección de Cartas",
                "team_a": "Tu Mano",
                "team_b": "Mano del Crupier",
                "cards_team_a": "Tus Cartas",
                "cards_team_b": "Cartas del Crupier",
                "points": "puntos",
                "take_snapshot": "Detectar Cartas",
                "capturing_cards": "Detectando cartas... Por favor espera.",
                "cards_detected": "¡Cartas detectadas correctamente!",
                "no_cards_detected": "No se detectaron cartas. Por favor intenta de nuevo.",
                "flip_cards": "Intercambiar Manos",
                "scoring_options": "Análisis de Decisión",
                "game_mode": "Estrategia",
                "bonus_points_team_a": "Apuesta (Tu Mano)",
                "bonus_points_team_b": "Apuesta (Crupier)",
                "team_a_last_10": "¿Ganaste la última mano?",
                "update_scores": "Registrar Resultado",
                "scores_updated": "¡Resultado registrado!",
                "revert_last_round": "Deshacer Última Mano",
                "start_new_game": "Nueva Sesión",
                "new_game_started": "¡Nueva sesión iniciada!",
                "game_modes": ["Hit", "Stand", "Double", "Split"],
                "image_analyzed": "Imagen analizada",
                "upload_image": "Carga una imagen de cartas",
                "num_players": "Número de jugadores",
                "detection_mode": "Modo de detección",
                "manual": "Manual",
                "automatic": "Automático",
                "auto_detect_message": "El número de jugadores se detectará automáticamente.",
                "players_detected": "Jugadores Detectados",
                "player": "Jugador",
                "no_dealer_detected": "⚠️ No hay dealer detectado.",
                "not_enough_cards": "⚠️ Se necesitan al menos 2 cartas para dar una recomendación.",
                "player_hand": "Mano",
                "dealer_upcard": "Carta visible del dealer",
                "hit_desc": "Pide otra carta.",
                "stand_desc": "Plantarse. Tu mano es suficientemente fuerte.",
                "double_desc": "Dobla tu apuesta y recibe exactamente una carta más.",
                "split_desc": "Divide tu par en dos manos independientes.",
                "blackjack_desc": "¡Blackjack! Ganas automáticamente.",
                "bust_desc": "Te has pasado de 21. Pierdes automáticamente.",
                "players_detected_debug": "jugadores detectados"
            },
        }

    def get(self, key):
        return self.texts[self.language].get(key, key)

    def get_modes(self):
        return self.texts[self.language]["game_modes"]
